# Generated by Django 2.1.5 on 2019-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfn', models.IntegerField()),
                ('dfnq', models.IntegerField()),
                ('dfns', models.IntegerField()),
                ('dfne', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='kejwckhfd',
            field=models.EmailField(blank=True, max_length=70, null=True),
        ),
    ]
