# Generated by Django 2.1.5 on 2019-02-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190209_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='kejwckhfd',
        ),
    ]
